// Mocks generated by Mockito 5.4.6 from annotations
// in crm_clinic/test/data/data_source_impl/get_all_doctors_datasource_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:crm_clinic/core/services/firebase_manager.dart' as _i4;
import 'package:crm_clinic/data/model/appointment_model.dart' as _i8;
import 'package:crm_clinic/data/model/patient_model.dart' as _i7;
import 'package:crm_clinic/data/model/user_model.dart' as _i6;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_1<T extends Object?> extends _i1.SmartFake
    implements _i3.QuerySnapshot<T> {
  _FakeQuerySnapshot_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSnapshotMetadata_2 extends _i1.SmartFake
    implements _i3.SnapshotMetadata {
  _FakeSnapshotMetadata_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_3<T1 extends Object?> extends _i1.SmartFake
    implements _i3.DocumentReference<T1> {
  _FakeDocumentReference_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseManager extends _i1.Mock implements _i4.FirebaseManager {
  MockFirebaseManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserCredential> registerService(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerService, [email, password]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#registerService, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> loginService(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginService, [email, password]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#loginService, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> signInWithFacebook() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithFacebook, []),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithFacebook, []),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> addUser({
    required _i6.UserModel? userModel,
    required _i2.UserCredential? userCredential,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addUser, [], {
              #userModel: userModel,
              #userCredential: userCredential,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addPatient(_i7.PatientModel? patientModel) =>
      (super.noSuchMethod(
            Invocation.method(#addPatient, [patientModel]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeDoc({
    required String? collection,
    required String? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeDoc, [], {
              #collection: collection,
              #id: id,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i3.QuerySnapshot<Map<String, dynamic>>> getAllDocsInCollection(
    String? collectionPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllDocsInCollection, [collectionPath]),
            returnValue:
                _i5.Stream<_i3.QuerySnapshot<Map<String, dynamic>>>.empty(),
          )
          as _i5.Stream<_i3.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i5.Future<_i3.QuerySnapshot<Map<String, dynamic>>> getDoctors() =>
      (super.noSuchMethod(
            Invocation.method(#getDoctors, []),
            returnValue:
                _i5.Future<_i3.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_1<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getDoctors, []),
                  ),
                ),
          )
          as _i5.Future<_i3.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i5.Future<_i6.UserPermission> getUserPermission(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPermission, [uid]),
            returnValue: _i5.Future<_i6.UserPermission>.value(
              _i6.UserPermission.admin,
            ),
          )
          as _i5.Future<_i6.UserPermission>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createDefaultAdminIfNotExists() =>
      (super.noSuchMethod(
            Invocation.method(#createDefaultAdminIfNotExists, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addAppointment(_i8.AppointmentModel? appointment) =>
      (super.noSuchMethod(
            Invocation.method(#addAppointment, [appointment]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<List<_i8.AppointmentModel>> getAppointmentsByDate(
    DateTime? date,
    String? doctorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAppointmentsByDate, [date, doctorId]),
            returnValue: _i5.Stream<List<_i8.AppointmentModel>>.empty(),
          )
          as _i5.Stream<List<_i8.AppointmentModel>>);

  @override
  _i5.Future<void> cancelAppointment({
    required String? appointmentId,
    required String? doctorId,
    required String? slotId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelAppointment, [], {
              #appointmentId: appointmentId,
              #doctorId: doctorId,
              #slotId: slotId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> addSlotForDoctor({
    required String? doctorId,
    required DateTime? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSlotForDoctor, [], {
              #doctorId: doctorId,
              #slot: slot,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeSlot({
    required String? doctorId,
    required String? slotId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeSlot, [], {
              #doctorId: doctorId,
              #slotId: slotId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i3.QuerySnapshot<Map<String, dynamic>>> getAllSlotsByDoctor(
    String? doctorId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllSlotsByDoctor, [doctorId]),
            returnValue:
                _i5.Stream<_i3.QuerySnapshot<Map<String, dynamic>>>.empty(),
          )
          as _i5.Stream<_i3.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i5.Future<_i3.QuerySnapshot<Map<String, dynamic>>>
  getAvailableSlotsForDoctor(String? doctorId) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableSlotsForDoctor, [doctorId]),
            returnValue:
                _i5.Future<_i3.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_1<Map<String, dynamic>>(
                    this,
                    Invocation.method(#getAvailableSlotsForDoctor, [doctorId]),
                  ),
                ),
          )
          as _i5.Future<_i3.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i5.Future<void> bookAppointmentAndUpdateSlot({
    required String? patientId,
    required String? doctorId,
    required String? doctorName,
    required String? slotId,
    required _i7.PatientModel? patient,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#bookAppointmentAndUpdateSlot, [], {
              #patientId: patientId,
              #doctorId: doctorId,
              #doctorName: doctorName,
              #slotId: slotId,
              #patient: patient,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateAppointment({
    required String? appointmentId,
    required String? oldDoctorId,
    required String? oldSlotId,
    required String? newDoctorId,
    required String? newDoctorName,
    required String? newSlotId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateAppointment, [], {
              #appointmentId: appointmentId,
              #oldDoctorId: oldDoctorId,
              #oldSlotId: oldSlotId,
              #newDoctorId: newDoctorId,
              #newDoctorName: newDoctorName,
              #newSlotId: newSlotId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [QuerySnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuerySnapshot<T extends Object?> extends _i1.Mock
    implements _i3.QuerySnapshot<T> {
  MockQuerySnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.QueryDocumentSnapshot<T>> get docs =>
      (super.noSuchMethod(
            Invocation.getter(#docs),
            returnValue: <_i3.QueryDocumentSnapshot<T>>[],
          )
          as List<_i3.QueryDocumentSnapshot<T>>);

  @override
  List<_i3.DocumentChange<T>> get docChanges =>
      (super.noSuchMethod(
            Invocation.getter(#docChanges),
            returnValue: <_i3.DocumentChange<T>>[],
          )
          as List<_i3.DocumentChange<T>>);

  @override
  _i3.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i3.SnapshotMetadata);

  @override
  int get size =>
      (super.noSuchMethod(Invocation.getter(#size), returnValue: 0) as int);
}

/// A class which mocks [QueryDocumentSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockQueryDocumentSnapshot<T extends Object?> extends _i1.Mock
    implements _i3.QueryDocumentSnapshot<T> {
  MockQueryDocumentSnapshot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i3.DocumentReference<T> get reference =>
      (super.noSuchMethod(
            Invocation.getter(#reference),
            returnValue: _FakeDocumentReference_3<T>(
              this,
              Invocation.getter(#reference),
            ),
          )
          as _i3.DocumentReference<T>);

  @override
  _i3.SnapshotMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeSnapshotMetadata_2(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i3.SnapshotMetadata);

  @override
  bool get exists =>
      (super.noSuchMethod(Invocation.getter(#exists), returnValue: false)
          as bool);

  @override
  T data() =>
      (super.noSuchMethod(
            Invocation.method(#data, []),
            returnValue: _i9.dummyValue<T>(this, Invocation.method(#data, [])),
          )
          as T);

  @override
  dynamic get(Object? field) =>
      super.noSuchMethod(Invocation.method(#get, [field]));

  @override
  dynamic operator [](Object? field) =>
      super.noSuchMethod(Invocation.method(#[], [field]));
}
