// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA48yWu4dObZX3RAgaetzG6kYvEhtunObI',
    appId: '1:945797982425:web:450a55811839999dbe76c8',
    messagingSenderId: '945797982425',
    projectId: 'crm-clinic-3bb78',
    authDomain: 'crm-clinic-3bb78.firebaseapp.com',
    storageBucket: 'crm-clinic-3bb78.firebasestorage.app',
    measurementId: 'G-8QMMZEFK4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVSn7jK5ccFVt5eFKHdeXb4whMrM5dr_0',
    appId: '1:945797982425:android:b670037631a6de65be76c8',
    messagingSenderId: '945797982425',
    projectId: 'crm-clinic-3bb78',
    storageBucket: 'crm-clinic-3bb78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2TQE4SL8UQeZCDIpWK_HSwachs2FyLfg',
    appId: '1:945797982425:ios:d84f366dee86a5f1be76c8',
    messagingSenderId: '945797982425',
    projectId: 'crm-clinic-3bb78',
    storageBucket: 'crm-clinic-3bb78.firebasestorage.app',
    iosBundleId: 'com.example.crmClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2TQE4SL8UQeZCDIpWK_HSwachs2FyLfg',
    appId: '1:945797982425:ios:d84f366dee86a5f1be76c8',
    messagingSenderId: '945797982425',
    projectId: 'crm-clinic-3bb78',
    storageBucket: 'crm-clinic-3bb78.firebasestorage.app',
    iosBundleId: 'com.example.crmClinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA48yWu4dObZX3RAgaetzG6kYvEhtunObI',
    appId: '1:945797982425:web:81fcbe5b3c649359be76c8',
    messagingSenderId: '945797982425',
    projectId: 'crm-clinic-3bb78',
    authDomain: 'crm-clinic-3bb78.firebaseapp.com',
    storageBucket: 'crm-clinic-3bb78.firebasestorage.app',
    measurementId: 'G-R9VK8PN45K',
  );
}
